package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"task-tracker-backend/internal/graph"
	"task-tracker-backend/internal/model"
	"task-tracker-backend/internal/utils"
)

// RefreshToken is the resolver for the refreshToken mutation.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshToken) (string, error) {
	username, err := utils.ParseToken(input.Token)
	utils.HandleError(err)

	token, err := utils.GenerateToken(username)
	utils.HandleError(err)
	return token, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
